service: every-sentence

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-2
  ecr:
    images:
      everysentence:
        path: ./

functions:
  api: 
    image:
      name: everysentence
      entryPoint:
        - '/lambda-entrypoint.sh'
    # handler: src/lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
    